<?php
?>

<!DOCTYPE HTML> <html> <head> <p><a href="test9.html"></a>&nbsp;
    &nbsp;
    <a href="test11.html"></a></p><p></p><canvas id="mycanvas" width="600" height="600"></canvas><script type="text/javascript"> function drawShape(){ var canvas = document.getElementById('mycanvas');
      if (canvas.getContext){ var ctx = canvas.getContext('2d');
        ctx.beginPath();
        ctx.moveTo(150,0);
        ctx.lineTo(200,50);
        ctx.lineTo(200,100);
        ctx.lineTo(150,150);
        ctx.lineTo(100,100);
        ctx.lineTo(100,50);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#006400";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(5, 150, 75);
        ctx.beginPath();
        ctx.moveTo(250,0);
        ctx.lineTo(300,50);
        ctx.lineTo(300,100);
        ctx.lineTo(250,150);
        ctx.lineTo(200,100);
        ctx.lineTo(200,50);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#8b0000";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(2, 250, 75);
        ctx.beginPath();
        ctx.moveTo(350,0);
        ctx.lineTo(400,50);
        ctx.lineTo(400,100);
        ctx.lineTo(350,150);
        ctx.lineTo(300,100);
        ctx.lineTo(300,50);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#006400";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(6, 350, 75);
        ctx.beginPath();
        ctx.moveTo(100,100);
        ctx.lineTo(150,150);
        ctx.lineTo(150,200);
        ctx.lineTo(100,250);
        ctx.lineTo(50,200);
        ctx.lineTo(50,150);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#7cfc00";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(10, 100, 175);
        ctx.beginPath();
        ctx.moveTo(200,100);
        ctx.lineTo(250,150);
        ctx.lineTo(250,200);
        ctx.lineTo(200,250);
        ctx.lineTo(150,200);
        ctx.lineTo(150,150);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#006400";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(9, 200, 175);
        ctx.beginPath();
        ctx.moveTo(300,100);
        ctx.lineTo(350,150);
        ctx.lineTo(350,200);
        ctx.lineTo(300,250);
        ctx.lineTo(250,200);
        ctx.lineTo(250,150);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#7cfc00";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(4, 300, 175);
        ctx.beginPath();
        ctx.moveTo(400,100);
        ctx.lineTo(450,150);
        ctx.lineTo(450,200);
        ctx.lineTo(400,250);
        ctx.lineTo(350,200);
        ctx.lineTo(350,150);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#ffd700";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(3, 400, 175);
        ctx.beginPath();
        ctx.moveTo(50,200);
        ctx.lineTo(100,250);
        ctx.lineTo(100,300);
        ctx.lineTo(50,350);
        ctx.lineTo(0,300);
        ctx.lineTo(0,250);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#8b0000";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(8, 50, 275);
        ctx.beginPath();
        ctx.moveTo(150,200);
        ctx.lineTo(200,250);
        ctx.lineTo(200,300);
        ctx.lineTo(150,350);
        ctx.lineTo(100,300);
        ctx.lineTo(100,250);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#8b0000";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(11, 150, 275);
        ctx.beginPath();
        ctx.moveTo(250,200);
        ctx.lineTo(300,250);
        ctx.lineTo(300,300);
        ctx.lineTo(250,350);
        ctx.lineTo(200,300);
        ctx.lineTo(200,250);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#7cfc00";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(7, 250, 275);
        ctx.beginPath();
        ctx.moveTo(350,200);
        ctx.lineTo(400,250);
        ctx.lineTo(400,300);
        ctx.lineTo(350,350);
        ctx.lineTo(300,300);
        ctx.lineTo(300,250);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#7cfc00";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(5, 350, 275);
        ctx.beginPath();
        ctx.moveTo(450,200);
        ctx.lineTo(500,250);
        ctx.lineTo(500,300);
        ctx.lineTo(450,350);
        ctx.lineTo(400,300);
        ctx.lineTo(400,250);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#8b0000";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(8, 450, 275);
        ctx.beginPath();
        ctx.moveTo(100,300);
        ctx.lineTo(150,350);
        ctx.lineTo(150,400);
        ctx.lineTo(100,450);
        ctx.lineTo(50,400);
        ctx.lineTo(50,350);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#8b0000";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(4, 100, 375);
        ctx.beginPath();
        ctx.moveTo(200,300);
        ctx.lineTo(250,350);
        ctx.lineTo(250,400);
        ctx.lineTo(200,450);
        ctx.lineTo(150,400);
        ctx.lineTo(150,350);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#006400";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(3, 200, 375);
        ctx.beginPath();
        ctx.moveTo(300,300);
        ctx.lineTo(350,350);
        ctx.lineTo(350,400);
        ctx.lineTo(300,450);
        ctx.lineTo(250,400);
        ctx.lineTo(250,350);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#808080";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(6, 300, 375);
        ctx.beginPath();
        ctx.moveTo(400,300);
        ctx.lineTo(450,350);
        ctx.lineTo(450,400);
        ctx.lineTo(400,450);
        ctx.lineTo(350,400);
        ctx.lineTo(350,350);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#8b0000";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(10, 400, 375);
        ctx.beginPath();
        ctx.moveTo(150,400);
        ctx.lineTo(200,450);
        ctx.lineTo(200,500);
        ctx.lineTo(150,550);
        ctx.lineTo(100,500);
        ctx.lineTo(100,450);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#ffd700";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(11, 150, 475);
        ctx.beginPath();
        ctx.moveTo(250,400);
        ctx.lineTo(300,450);
        ctx.lineTo(300,500);
        ctx.lineTo(250,550);
        ctx.lineTo(200,500);
        ctx.lineTo(200,450);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#7cfc00";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(12, 250, 475);
        ctx.beginPath();
        ctx.moveTo(350,400);
        ctx.lineTo(400,450);
        ctx.lineTo(400,500);
        ctx.lineTo(350,550);
        ctx.lineTo(300,500);
        ctx.lineTo(300,450);
        ctx.closePath();
        ctx.lineWidth=1;
        ctx.strokeStyle='black';
        ctx.fillStyle="#7cfc00";
        ctx.fill();
        ctx.font = '20pt Calibri';
        ctx.fillStyle='black';
        ctx.textAlign='center';
        ctx.fillText(9, 350, 475);
        ctx.beginPath();
        ctx.rect(25, 138, 50, 25);
        ctx.fillStyle = 'brown';
        ctx.fill();
        ctx.beginPath();
        ctx.rect(125, 188, 50, 25);
        ctx.fillStyle = 'green';
        ctx.fill();
        ctx.beginPath();
        ctx.rect(175, 238, 50, 25);
        ctx.fillStyle = 'red';
        ctx.fill();
      } else { alert('You need Safari or Firefox 1.5+ to see this demo.');
      } } </script>  <div float:right; ><table border="1"> <col /> <col style="background-color: brown;
        color: #ffffff" /> <col style="background-color: blue;
        color: #ffffff" /> <col style="background-color: red;
        color: #ffffff" /> <col style="background-color: green;
        color: #ffffff" /></table></div></head> <body onload="drawShape(); drawScore(); "> </body> </html></head> <body onload="drawShape(); drawScore(); "> </body> </html>





